### ISSUE TITLE
@jcbhmr initiative

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/.github#3]
_I know it's somewhat arrogant to call this the "@jcbhmr initiative", but I couldn't think of a more generalized name to describe the vastness of the stuff that this issue entails._

## Proposition

Right now this repository _appears_ to have a single "anchor" repository: the features repository. This is good, but I think this organization can be much more than just a features collection. I propose that we...
1. Expand to cover images, features, and templates
2. Add some target issues for what features/images/templates we want
3. Create web interfaces for browsing features/images/templates instead of `README.md`s in GitHub
4. Add more metadata and scope-defining goals and goalposts to this metadata repo
5. Enable organization discussions

Here's a draft charter/objective document that I wrote down: [jcbhmr/devcontainers-contrib#jcbhmr-initiative](https://github.com/jcbhmr/devcontainers-contrib-.github/tree/jcbhmr-initiative#readme)

### Why we should expand the scope of this organization beyond just features
1. I thought that's what the name "devcontainers-contrib" entailed: more stuff beyond the boundaries set by the official devcontainers org
2. I believe this org _could_ become the "community hub" for devcontainers if played right
3. I want more images besides those that devcontainers/images offers, and this seems like the best spot

## Tasks
- [x] Create a .github repository
- [x] Create a features repository
- [ ] Create a docs website for those features
- [ ] Create a images repository
- [ ] Create a docs website for those images
- [x] Create a templates repository
- [x] Create a docs website for those templates
- [ ] Enable organization discussions and tie them to this .github repo
- [x] Create a README.md in this .github repo to outline the charter/objective
- [x] Add links for all the things to the .github/profile/README.md organization page
- [ ] Document code conventions and other stylistic decisions in the .github wiki (for devs)

<s>

### Ideas
These are things that I thought about and dismissed, but wanted to record and share.

<ul>
  <li>Create a devcontainers-contrib.github.io to host a landing page
  <li><details><summary>Rename this organization to something shorter than 21 characters (high friction, I know)</summary>
    <p>Ideas:</p>
    <ul>
      <li>✅ devcontainersx
      <li>✅ xdevcontainers
      <li>✅ devtainers
      <li>❌ devenv
      <li>✅ envtainers
      <li>✅ devenvcontainers
      <li>✅ devpreset
      <li>✅ codevenv
    </ul>
  </details></li>
</ul>

</s>

**Comment by jcbhmr** [comment]
Now that we have discussion going on exactly what belongs at what level... When we reach some kind of consensus (@jcbhmr shouldn't make all the decisions) it might be a good idea to either:
1. Publish those "what goes where" to the devcontainers-contrib.github.io website OR
2. Publish those "what goes where" to the dev wiki somewhere

/cc @danielbraun89 This is my next "documentation spree" that I'd like to tackle.

**Comment by jcbhmr** [comment]
@jcbhmr's progress on those tasks (in personal forks/copies of the repos they should target): \
_will be updated as progress is made_
- [x] ~~Create a .github repository~~
- [x] ~~Create a features repository~~
- [ ] Create a docs website for those features
- [ ] Create a images repository
- [ ] Create a docs website for those images
- [ ] ~~Create a templates repository~~ Create a _better_ templates repository
- [ ] Create a docs website for those templates
- [ ] ~~Enable organization discussions and tie them to this .github repo~~ (can't do)
- [x] [Create a README.md in this .github repo to outline the charter/objective](https://github.com/jcbhmr/devcontainers-contrib-.github/tree/jcbhmr-initiative#readme)
- [x] [Add links for all the things to the .github/profile/README.md organization page](https://github.com/jcbhmr/devcontainers-contrib-.github/tree/jcbhmr-initiative/profile)
- [ ] Document code conventions and other stylistic decisions in the .github wiki (for devs)

/cc @danielbraun89

**Comment by jcbhmr** [comment]
I no longer think this is realistic to expect given the discussion in https://github.com/devcontainers-contrib/features/issues/316
